name: Create Archive
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'csmp6-modpack.mrpack'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "csmp6-modpack.mrpack"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.event.head_commit.message }}
        tag: ${{ github.run_id }}
        commit: ${{ github.sha }}
